version: "3"

services:
  go:
    build:
      context: build/docker/go
    image: golang:1.16-alpine
    container_name: oa-go
    volumes:
      - "./:/go/src"
    networks:
      - bot
  prometheus:
    image: prom/prometheus:latest
    container_name: oa-prometheus
    volumes:
      - "./data/prometheus:/prometheus"
      - "./build/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - bot
  grafana:
    image: grafana/grafana:latest
    container_name: oa-grafana
    volumes:
      - "./data/grafana:/var/lib/grafana"
    networks:
      - bot

networks:
  bot:
    external: true
    name: bot