version: "3"

services:
  go:
    build:
      context: build/docker/go
    image: golang:1.16-alpine
    container_name: bot-go
    volumes:
      - "./:/go/src"
    networks:
      - bot
  postgres:
    image: postgres
    container_name: bot-postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
  pgadmin:
    image: dpage/pgadmin4
    container_name: bot-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - "./data/pgadmin:/var/lib/pgadmin"
  prometheus:
    image: prom/prometheus:latest
    container_name: bot-prometheus
    volumes:
      - "./data/prometheus:/prometheus"
      - "./build/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - bot
  grafana:
    image: grafana/grafana:latest
    container_name: bot-grafana
    volumes:
      - "./data/grafana:/var/lib/grafana"
    networks:
      - bot
  graylog:
    image: graylog/graylog:4.1
    container_name: bot-graylog
    environment:
      - GRAYLOG_ROOT_USERNAME=${GRAYLOG_USERNAME}
      - GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PASSWORD}
      - GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2}
      - GRAYLOG_HTTP_EXTERNAL_URI=${GRAYLOG_UI_URI}
      - GRAYLOG_MONGODB_URI=${GRAYLOG_MONGODB_URI}
      - GRAYLOG_ELASTICSEARCH_HOSTS=${GRAYLOG_ELASTICSEARCH_HOSTS}
    volumes:
      - "./data/graylog/data/journal:/usr/share/graylog/data/journal"
    depends_on:
      - graylog-mongo
      - graylog-elasticsearch
    restart: always
    networks:
      - bot
  graylog-mongo:
    image: mongo:4.2
    container_name: bot-graylog-mongo
    volumes:
      - "./data/graylog/data/mongo:/data/db"
    networks:
      - bot
  graylog-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: bot-graylog-elasticsearch
    volumes:
      - "./data/graylog/data/elasticsearch:/usr/share/elasticsearch/data"
      - "./data/graylog/data/elasticsearch/nodes:/usr/share/elasticsearch/data/nodes"
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - bot
networks:
  bot:
    external: true
    name: bot